# Generated by Django 4.2.11 on 2024-06-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('task', '0002_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='catagory',
        ),
        migrations.AddField(
            model_name='task',
            name='catagory',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
